[CmdletBinding()]
param(
    [string]$SyncPath,
    [string]$AgentName = "CODEX",
    [string]$InboxPath,
    [switch]$NoAutoAck,
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-KstTimestamp {
    $tz = [System.TimeZoneInfo]::FindSystemTimeZoneById("Korea Standard Time")
    $kst = [System.TimeZoneInfo]::ConvertTimeFromUtc([DateTime]::UtcNow, $tz)
    return $kst.ToString("yyyy-MM-dd HH:mm 'KST'")
}

function Extract-FieldValue {
    param(
        [string]$Block,
        [string]$FieldName
    )
    $pattern = "(?mi)^\s*" + [regex]::Escape($FieldName) + "\s*:\s*(.+?)\s*$"
    $m = [regex]::Match($Block, $pattern)
    if ($m.Success) {
        return $m.Groups[1].Value.Trim()
    }
    return ""
}

function Parse-Messages {
    param([string]$RawContent)

    $blocks = [regex]::Split($RawContent, "(?m)^\s*---\s*$")
    $messages = @()
    foreach ($block in $blocks) {
        if ($block -notmatch "\[SEQ:\d+\]") {
            continue
        }

        $headerMatch = [regex]::Match($block, "(?m)^\s*\[SEQ:(\d+)\]\s*\[(.*?)\]\s*\[(.*?)\]\s*\[(.*?)\]\s*$")
        if (-not $headerMatch.Success) {
            continue
        }

        $seq = [int]$headerMatch.Groups[1].Value
        $timestamp = $headerMatch.Groups[2].Value.Trim()
        $route = $headerMatch.Groups[3].Value.Trim()
        $headerType = $headerMatch.Groups[4].Value.Trim()
        $headerTypeNormalized = $headerType -replace "^(?i:TYPE\s*:\s*)", ""
        $typeValue = Extract-FieldValue -Block $block -FieldName "TYPE"
        if (-not $typeValue) {
            $typeValue = $headerTypeNormalized
        }

        $expectsAckRaw = Extract-FieldValue -Block $block -FieldName "EXPECTS_ACK"
        $expectsAck = $expectsAckRaw -match "^(?i:true|yes|1)$"

        $what = Extract-FieldValue -Block $block -FieldName "WHAT"
        $ackFor = Extract-FieldValue -Block $block -FieldName "ACK_FOR"

        $from = ""
        $to = ""
        if ($route -match "^\s*(.+?)\s*->\s*(.+?)\s*$") {
            $from = $Matches[1].Trim()
            $to = $Matches[2].Trim()
        }

        $messages += [pscustomobject]@{
            Seq        = $seq
            Timestamp  = $timestamp
            Route      = $route
            From       = $from
            To         = $to
            HeaderType = $headerType
            Type       = $typeValue
            ExpectsAck = $expectsAck
            What       = $what
            AckFor     = $ackFor
            RawBlock   = $block.Trim()
        }
    }
    return $messages
}

$scriptRoot = Split-Path -Parent $PSCommandPath
$resonanceRoot = Split-Path -Parent $scriptRoot

if (-not $SyncPath) {
    $SyncPath = Join-Path $resonanceRoot "RESONANCE_SYNC.md"
}
if (-not $InboxPath) {
    $InboxPath = Join-Path $resonanceRoot ("shared\" + $AgentName.ToLowerInvariant() + "_inbox.md")
}

if (-not (Test-Path -LiteralPath $SyncPath)) {
    throw "Sync file not found: $SyncPath"
}

$raw = Get-Content -Path $SyncPath -Raw
$messages = Parse-Messages -RawContent $raw
if ($messages.Count -eq 0) {
    Write-Host "No SEQ messages found."
    exit 0
}

$maxSeq = ($messages | Measure-Object -Property Seq -Maximum).Maximum

$ackedSeqSet = New-Object System.Collections.Generic.HashSet[int]
foreach ($m in $messages) {
    if ($m.Type -match "^(?i:ACK)$" -and $m.AckFor -match "SEQ:(\d+)") {
        [void]$ackedSeqSet.Add([int]$Matches[1])
    }
}

$pending = @()
foreach ($m in $messages) {
    if (-not $m.ExpectsAck) {
        continue
    }
    if ($m.To -notmatch ("(?i)\b" + [regex]::Escape($AgentName) + "\b")) {
        continue
    }
    if ($ackedSeqSet.Contains([int]$m.Seq)) {
        continue
    }
    $pending += $m
}

if ($pending.Count -eq 0) {
    Write-Host "No pending ACK-required messages for $AgentName."
}
else {
    Write-Host ("Pending ACK-required messages for {0}: {1}" -f $AgentName, $pending.Count)
}

$inboxLines = @()
$inboxLines += ("# " + $AgentName + " Inbox")
$inboxLines += ""
$inboxLines += ("Last sync scan: " + (Get-KstTimestamp))
$inboxLines += ("Sync file: " + $SyncPath)
$inboxLines += ""
$inboxLines += "## Pending Messages"
$inboxLines += ""

if ($pending.Count -eq 0) {
    $inboxLines += "- None"
}
else {
    foreach ($p in $pending | Sort-Object Seq) {
        $inboxLines += ("- [ ] SEQ:{0} | TYPE:{1} | FROM:{2} | WHAT:{3}" -f $p.Seq.ToString("000"), $p.Type, $p.From, $p.What)
    }
}

$inboxLines += ""
$inboxLines += "## Notes"
$inboxLines += ""
$inboxLines += "- This file is generated by tools/boot_sync.ps1."
$inboxLines += "- Mark checkboxes only after actual work is completed."

$inboxContent = ($inboxLines -join "`n") + "`n"
if ($DryRun) {
    Write-Host ("[DRYRUN] would write inbox: " + $InboxPath)
}
else {
    $inboxDir = Split-Path -Parent $InboxPath
    if (-not (Test-Path -LiteralPath $inboxDir)) {
        New-Item -ItemType Directory -Path $inboxDir -Force | Out-Null
    }
    Set-Content -Path $InboxPath -Value $inboxContent -Encoding UTF8
}

if ($NoAutoAck -or $pending.Count -eq 0) {
    exit 0
}

$appendBlocks = @()
foreach ($p in ($pending | Sort-Object Seq)) {
    $maxSeq += 1
    $seqStr = $maxSeq.ToString("000")
    $ackTarget = if ($p.From) { $p.From } else { "ANTIGRAVITY" }
    $ackBlock = @"
---
[SEQ:$seqStr] [$(Get-KstTimestamp)] [$AgentName->$ackTarget] [TYPE: ACK]
TYPE: ACK
ACK_FOR: SEQ:$($p.Seq.ToString("000"))
WHAT: Auto-acknowledged by boot sequence scanner.
DETAIL: Detected pending ACK-required message for $AgentName and acknowledged automatically.
EXPECTS_ACK: false
FILES_TOUCHED: $SyncPath
---
"@
    $appendBlocks += $ackBlock
}

if ($DryRun) {
    Write-Host ("[DRYRUN] would append {0} ACK block(s)" -f $appendBlocks.Count)
}
else {
    Add-Content -Path $SyncPath -Value ($appendBlocks -join "`n") -Encoding UTF8
    Write-Host ("Appended {0} ACK block(s)." -f $appendBlocks.Count)
}
